import React from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { SEO } from '../components/SEO';
import { useSmartBack } from '../hooks/useSmartBack';
import { motion } from 'framer-motion';

interface LegalProps {
  defaultTab?: 'privacy' | 'terms' | 'refund' | 'shipping' | 'delete';
}

export const Legal: React.FC<LegalProps> = ({ defaultTab }) => {
  const [searchParams] = useSearchParams();
  const goBack = useSmartBack('/');
  const currentTab = defaultTab || searchParams.get('tab') || 'terms';

  const isTerms = currentTab === 'terms';
  const isPrivacy = currentTab === 'privacy';
  const isDelete = currentTab === 'delete';

  return (
    <motion.div 
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: 'easeOut' }}
      className="min-h-screen bg-white text-gray-900 flex flex-col font-sans"
    >
      <SEO
        title={`${isTerms ? 'FreshCart Terms of Use' : isPrivacy ? 'Privacy Notice' : isDelete ? 'Delete Your Account' : 'Legal Policy'} | FreshCart`}
        description={isDelete
          ? 'How to request deletion of your FreshCart account and what happens to your data.'
          : 'Official legal policies, customer terms of service, and privacy guidelines for FreshCart Marketplace Private Limited.'}
      />

      {/* Clean White Standalone Header with Brand Logo Only */}
      <header className="bg-white py-4 px-6 md:px-16 flex items-center gap-3 border-b border-gray-200 sticky top-0 z-40 shadow-2xs">
        <button
          onClick={goBack}
          aria-label="Go back"
          className="w-9 h-9 rounded-full bg-gray-100 hover:bg-gray-200 flex items-center justify-center text-gray-800 transition-colors cursor-pointer shrink-0"
        >
          <ArrowLeft size={18} />
        </button>
        <Link to="/" className="flex items-center gap-2">
          <span className="text-[26px] md:text-[36px] font-extrabold tracking-tight text-gray-900 font-display leading-none">
            fresh<span className="text-[#4CAF50]">cart</span>
          </span>
        </Link>
      </header>

      {/* Centered Page Title Banner */}
      <div className="bg-gray-50 py-8 px-6 text-center border-b border-gray-200">
        <h1 className="text-2xl md:text-3xl font-black text-gray-900 underline underline-offset-8 font-display">
          {isTerms ? 'FreshCart Terms of Use' : isPrivacy ? 'Privacy Notice' : isDelete ? 'Delete Your Account' : 'FreshCart Policies'}
        </h1>
      </div>

      {/* Main Document Body */}
      <main className="flex-1 w-full max-w-[900px] mx-auto px-6 md:px-12 py-8 text-gray-800 text-sm md:text-base leading-relaxed flex flex-col gap-6">
        
        {/* Version & Date Metadata */}
        {!isDelete && (
          <div className="flex flex-col gap-1 border-b border-gray-200 pb-4">
            <span className="text-sm md:text-base font-extrabold text-gray-900">
              {isTerms ? 'Version 1.4' : 'Version 1.1'}
            </span>
            <span className="text-xs md:text-sm font-bold text-gray-600">
              {isTerms ? 'Last updated: 1 st November 2025' : 'Last updated: 17th June 2025'}
            </span>
          </div>
        )}

        {/* Legal Preamble */}
        {!isDelete && (
          <p className="text-xs md:text-sm text-gray-600 leading-relaxed">
            This document is an electronic record and published in accordance with the provisions of the Information Technology Act, 2000 and the rules thereunder and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and generated by a computer system and does not require any physical or digital signatures.
          </p>
        )}

        {/* Delete Account Content Section */}
        {isDelete && (
          <div className="flex flex-col gap-6">
            <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
              You can request deletion of your FreshCart account and associated personal data at any time.
              Deletion is permanent and cannot be undone.
            </p>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">1. Delete from the FreshCart app</h2>
              <ol className="list-decimal list-inside text-xs md:text-sm text-gray-700 leading-relaxed space-y-1.5">
                <li>Open the FreshCart app and sign in.</li>
                <li>Go to <strong className="text-gray-900">Account</strong>.</li>
                <li>Tap <strong className="text-gray-900">Delete account</strong> at the bottom of the screen and confirm.</li>
              </ol>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">2. Delete from freshcart.com</h2>
              <ol className="list-decimal list-inside text-xs md:text-sm text-gray-700 leading-relaxed space-y-1.5">
                <li>Sign in and open your <Link to="/account/profile" className="text-[#4CAF50] font-bold hover:underline">Account</Link> page.</li>
                <li>Tap <strong className="text-gray-900">Edit</strong> on your profile.</li>
                <li>Tap <strong className="text-gray-900">Delete account</strong>, then tap it again to confirm.</li>
              </ol>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">3. Can't sign in?</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                Email <a href="mailto:support@freshcart.com?subject=Account%20deletion%20request" className="text-[#4CAF50] font-bold hover:underline">support@freshcart.com</a> from
                your registered email address (or with your registered phone number) with the subject "Account deletion request".
                We verify the request and delete the account within 7 business days.
              </p>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">4. What gets deleted</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed mb-3">
                4.1. Your profile, saved addresses, wallet balance, saved cards/UPI handles, wishlist and reviews are permanently removed.
              </p>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                4.2. Past order records are retained in de-identified form as required for accounting, tax and fraud-prevention
                obligations under Indian law, and are no longer linked to your name, phone number or address.
              </p>
            </div>
          </div>
        )}

        {/* Terms Content Section */}
        {isTerms && (
          <div className="flex flex-col gap-6">
            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">1. Terms of Use</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed mb-3">
                1.1. The websites <strong className="text-gray-900">www.freshcart.com</strong>, <strong className="text-gray-900">www.freshcartnow.com</strong> ("Website") and mobile application 'FreshCart' (<strong className="text-gray-900">App</strong>) (Website and App collectively referred to as the "<strong className="text-gray-900">Platform</strong>") is owned, operated and managed by FreshCart Marketplace Private Limited, a private limited company incorporated in accordance with the provisions of the Indian Companies Act, 2013 having its registered office situated at First Floor, 773, Sarjapur Main Road, Bengaluru, Karnataka-560103.
              </p>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                1.2. These terms of use ("Terms") govern your use of the Platform, and for the purpose of these Terms, FreshCart Marketplace Private Limited including its subsidiaries, its holding company, its affiliates may wherever context so require, be also referred to as, "FreshCart", "We", "Us", or "Our".
              </p>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">2. Services & 10-Minute Delivery Commitment</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed mb-3">
                2.1. FreshCart enables quick-commerce delivery of groceries, fresh fruits, vegetables, dairy, household items, and personal care products directly to your designated address via localized dark stores.
              </p>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                2.2. Displayed delivery estimates (e.g. 10 minutes) are target timeframes subject to active rider availability, traffic regulations, bad weather conditions, and accurate delivery location details provided by the user.
              </p>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">3. User Account & Security</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed mb-3">
                3.1. You are responsible for maintaining the confidentiality of your mobile number and OTP authentication credentials. All actions originating from your registered account shall be deemed to be authorized by you.
              </p>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                3.2. FreshCart reserves the right to suspend or terminate accounts engaging in fraudulent orders, abusive behavior toward delivery partners, or violation of applicable laws.
              </p>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">4. Pricing, Payments & Invoicing</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                4.1. Prices displayed on the Platform are inclusive of applicable taxes unless stated otherwise. The final bill amount generated upon checkout is payable via UPI, credit/debit card, net banking, or cash on delivery.
              </p>
            </div>
          </div>
        )}

        {/* Privacy Content Section */}
        {isPrivacy && (
          <div className="flex flex-col gap-6">
            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">1. Privacy Notice Overview</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed mb-3">
                1.1. This Notice applies to FreshCart Marketplace Private Limited (hereinafter referred to as "FreshCart" or "the Company"), a company incorporated under the Companies Act, 2013 and having its registered office at First Floor, 773, Sarjapur Main Road, Bengaluru, Karnataka-560103. The Company is the owner of websites <strong className="text-gray-900">www.freshcart.com</strong>, <strong className="text-gray-900">www.freshcartnow.com</strong> and mobile application 'FreshCart' (collectively, the "<strong className="text-gray-900">Platform</strong>").
              </p>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                1.2. This privacy notice (Privacy Notice) describes the policies and procedures applicable to the collection, use, storage, disclosure and protection of Your information shared with Us while You use the Platform, and for the purpose of this Privacy Notice "We", "Us", or "Our" refers to FreshCart Marketplace Private Limited and its subsidiaries. We value the trust You place in Us. That is why, We maintain reasonable security standards for securing the transactions and Your information.
              </p>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">2. Information We Collect</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed mb-3">
                2.1. <strong className="text-gray-900">Personal Information:</strong> We collect your mobile number, delivery address, contact name, and order preferences to fulfill grocery deliveries.
              </p>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                2.2. <strong className="text-gray-900">Location Data:</strong> With your permission, we query real-time GPS coordinates to display nearby available product catalogs and enable real-time dispatch tracking.
              </p>
            </div>

            <div>
              <h2 className="text-base md:text-lg font-extrabold text-gray-900 mb-2">3. Data Protection & Security</h2>
              <p className="text-xs md:text-sm text-gray-700 leading-relaxed">
                3.1. All online payments are processed through PCI-DSS certified payment gateways. FreshCart does not store credit or debit card numbers on our servers. Your data is protected using industry-standard encryption protocols.
              </p>
            </div>
          </div>
        )}

        {/* Legal Footer Note */}
        <div className="mt-8 border-t border-gray-200 pt-6 text-center text-xs text-gray-500">
          © {new Date().getFullYear()} FreshCart Marketplace Private Limited. All rights reserved.
        </div>

      </main>
    </motion.div>
  );
};
