import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import 'package:freshcart/features/categories/data/models/category_model.dart';
import 'package:freshcart/features/products/data/models/product_model.dart';

class MockDataService {

  MockDataService._();

  static final List<CategoryModel> categories = [
    const CategoryModel(
      id: 'cat_organic',
      name: 'Organic',
      icon: 'organic',
      color: Color(0xFF34C759),
      productCount: 12,
    ),
    const CategoryModel(
      id: 'cat_veg',
      name: 'Vegetables',
      icon: 'vegetables',
      color: Color(0xFF4CAF50),
      productCount: 18,
    ),
    const CategoryModel(
      id: 'cat_fruits',
      name: 'Fruits',
      icon: 'fruits',
      color: Color(0xFFFF9500),
      productCount: 15,
    ),
    const CategoryModel(
      id: 'cat_bakery',
      name: 'Bakery',
      icon: 'bakery',
      color: Color(0xFF8E8E93),
      productCount: 10,
    ),
    const CategoryModel(
      id: 'cat_dairy',
      name: 'Dairy',
      icon: 'dairy',
      color: Color(0xFF007AFF),
      productCount: 14,
    ),
    const CategoryModel(
      id: 'cat_meat',
      name: 'Meat & Seafood',
      icon: 'meat',
      color: Color(0xFFFF3B30),
      productCount: 8,
    ),
    const CategoryModel(
      id: 'cat_snacks',
      name: 'Snacks',
      icon: 'snacks',
      color: Color(0xFFAF52DE),
      productCount: 22,
    ),
    const CategoryModel(
      id: 'cat_drinks',
      name: 'Beverages',
      icon: 'beverages',
      color: Color(0xFF5AC8FA),
      productCount: 16,
    ),
  ];

  static final List<ProductModel> products = [
    // Organic Products
    const ProductModel(
      id: 'prod_org_1',
      name: 'Organic Baby Spinach',
      brand: 'Earth Greens',
      categoryId: 'cat_organic',
      rating: 4.8,
      reviewsCount: 320,
      price: 99.0,
      mrp: 120.0,
      discountText: '17% OFF',
      weightOptions: ['150g', '300g'],
      defaultWeight: '150g',
      description: 'Farm-fresh organic baby spinach leaves, pre-washed and ready to eat. Perfect for salads, smoothies, or sautéing. Packed with Iron and Vitamins A & C.',
      nutritionFacts: {'Calories': '23 kcal', 'Protein': '2.9g', 'Carbs': '3.6g', 'Fiber': '2.2g'},
      ingredients: ['Organic Baby Spinach'],
      isOrganic: true,
      imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop',
      isFreshPick: true,
    ),
    const ProductModel(
      id: 'prod_org_2',
      name: 'Organic Hass Avocados',
      brand: 'Natures Choice',
      categoryId: 'cat_organic',
      rating: 4.7,
      reviewsCount: 412,
      price: 249.0,
      mrp: 299.0,
      discountText: '₹50 OFF',
      weightOptions: ['2 pcs', '4 pcs'],
      defaultWeight: '2 pcs',
      description: 'Rich, creamy organic Hass avocados sourced directly from organic orchards. High in healthy monounsaturated fats, potassium, and dietary fiber.',
      nutritionFacts: {'Calories': '160 kcal', 'Protein': '2g', 'Fat': '15g', 'Fiber': '7g'},
      ingredients: ['Organic Avocado'],
      isOrganic: true,
      imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&auto=format&fit=crop',
      isBestSeller: true,
    ),
    const ProductModel(
      id: 'prod_org_3',
      name: 'Organic Raw Honey',
      brand: 'Golden Farms',
      categoryId: 'cat_organic',
      rating: 4.9,
      reviewsCount: 154,
      price: 199.0,
      mrp: 250.0,
      discountText: '20% OFF',
      weightOptions: ['250g', '500g'],
      defaultWeight: '250g',
      description: '100% pure, raw, unpasteurized organic honey collected from wildflowers. Rich in natural antioxidants and enzymes.',
      nutritionFacts: {'Calories': '64 kcal', 'Protein': '0g', 'Carbs': '17g', 'Sugars': '16g'},
      ingredients: ['Organic Wildflower Honey'],
      isOrganic: true,
      imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
    
    // Vegetables Products
    const ProductModel(
      id: 'prod_veg_1',
      name: 'Fresh Cherry Tomatoes',
      brand: 'FarmDirect',
      categoryId: 'cat_veg',
      rating: 4.6,
      reviewsCount: 180,
      price: 59.0,
      mrp: 75.0,
      discountText: '21% OFF',
      weightOptions: ['250g', '500g'],
      defaultWeight: '250g',
      description: 'Sweet, juicy vine-ripened cherry tomatoes. Excellent for salads, roasting, or snacking straight out of the box.',
      nutritionFacts: {'Calories': '18 kcal', 'Protein': '0.9g', 'Carbs': '3.9g', 'Vitamin C': '20%'},
      ingredients: ['Cherry Tomatoes'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop',
      isFreshPick: true,
    ),
    const ProductModel(
      id: 'prod_veg_2',
      name: 'Organic Broccoli Crowns',
      brand: 'Earth Greens',
      categoryId: 'cat_veg',
      rating: 4.5,
      reviewsCount: 220,
      price: 89.0,
      mrp: 110.0,
      discountText: '19% OFF',
      weightOptions: ['250g', '500g'],
      defaultWeight: '250g',
      description: 'Fresh broccoli crowns with compact florets and crisp stalks. Packed with antioxidants, vitamin K, and vitamin C.',
      nutritionFacts: {'Calories': '34 kcal', 'Protein': '2.8g', 'Carbs': '6.6g', 'Fiber': '2.6g'},
      ingredients: ['Organic Broccoli'],
      isOrganic: true,
      imageUrl: 'https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=500&auto=format&fit=crop',
      isFreshPick: true,
    ),
    const ProductModel(
      id: 'prod_veg_3',
      name: 'Fresh Orange Carrots',
      brand: 'FarmDirect',
      categoryId: 'cat_veg',
      rating: 4.7,
      reviewsCount: 145,
      price: 49.0,
      mrp: 60.0,
      discountText: '18% OFF',
      weightOptions: ['500g', '1kg'],
      defaultWeight: '500g',
      description: 'Sweet, crunchy orange carrots harvested daily. Perfect for juices, soups, salads, or cooking.',
      nutritionFacts: {'Calories': '41 kcal', 'Protein': '0.9g', 'Carbs': '9.6g', 'Vitamin A': '330%'},
      ingredients: ['Carrots'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),

    // Fruits Products
    const ProductModel(
      id: 'prod_fruit_1',
      name: 'Royal Gala Apples',
      brand: 'AppleCorp',
      categoryId: 'cat_fruits',
      rating: 4.9,
      reviewsCount: 890,
      price: 189.0,
      mrp: 240.0,
      discountText: '₹51 OFF',
      weightOptions: ['4 pcs (approx. 500g)', '1 kg'],
      defaultWeight: '4 pcs (approx. 500g)',
      description: 'Crisp, sweet, and aromatic Royal Gala apples imported from select orchards. Excellent source of dietary fiber and vitamin C.',
      nutritionFacts: {'Calories': '52 kcal', 'Protein': '0.3g', 'Carbs': '14g', 'Fiber': '2.4g'},
      ingredients: ['Gala Apples'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop',
      isBestSeller: true,
    ),
    const ProductModel(
      id: 'prod_fruit_2',
      name: 'Fresh Blueberries Box',
      brand: 'BerrySweet',
      categoryId: 'cat_fruits',
      rating: 4.7,
      reviewsCount: 310,
      price: 299.0,
      mrp: 350.0,
      discountText: '15% OFF',
      weightOptions: ['125g', '250g'],
      defaultWeight: '125g',
      description: 'Sweet and plump fresh blueberries. Packed with vitamins and high in antioxidants. Great for breakfast bowls or straight snacking.',
      nutritionFacts: {'Calories': '57 kcal', 'Carbs': '14g', 'Fiber': '2.4g', 'Vitamin C': '16%'},
      ingredients: ['Blueberries'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=500&auto=format&fit=crop',
      isFreshPick: true,
    ),
    const ProductModel(
      id: 'prod_fruit_3',
      name: 'Cavendish Bananas',
      brand: 'EcoFruit',
      categoryId: 'cat_fruits',
      rating: 4.8,
      reviewsCount: 420,
      price: 60.0,
      mrp: 80.0,
      discountText: '25% OFF',
      weightOptions: ['6 pcs (approx. 800g)', '12 pcs'],
      defaultWeight: '6 pcs (approx. 800g)',
      description: 'Fresh, sweet, and perfectly ripe Cavendish bananas. Excellent source of potassium and instant energy.',
      nutritionFacts: {'Calories': '89 kcal', 'Protein': '1.1g', 'Carbs': '23g', 'Potassium': '358mg'},
      ingredients: ['Bananas'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),

    // Dairy Products
    const ProductModel(
      id: 'prod_dairy_1',
      name: 'Premium Greek Yogurt',
      brand: 'DairyGold',
      categoryId: 'cat_dairy',
      rating: 4.8,
      reviewsCount: 450,
      price: 75.0,
      mrp: 90.0,
      discountText: '16% OFF',
      weightOptions: ['200g', '400g'],
      defaultWeight: '200g',
      description: 'Thick, creamy, and high-protein Greek yogurt. Sourced from grass-fed cows. Contains active live probiotic cultures for digestive health.',
      nutritionFacts: {'Calories': '130 kcal', 'Protein': '15g', 'Carbs': '6g', 'Calcium': '20%'},
      ingredients: ['Pasteurized Milk', 'Active Yogurt Cultures'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop',
      isBestSeller: true,
    ),
    const ProductModel(
      id: 'prod_dairy_2',
      name: 'Organic Whole Milk',
      brand: 'CowFresh',
      categoryId: 'cat_dairy',
      rating: 4.7,
      reviewsCount: 560,
      price: 68.0,
      mrp: 75.0,
      discountText: '9% OFF',
      weightOptions: ['1L', '500ml'],
      defaultWeight: '1L',
      description: 'Pure, organic whole pasteurized cow milk. Rich in vitamin D, calcium, and essential nutrients with a creamy, natural taste.',
      nutritionFacts: {'Calories': '150 kcal', 'Protein': '8g', 'Fat': '8g', 'Calcium': '30%'},
      ingredients: ['Organic Cow Milk', 'Vitamin D3'],
      isOrganic: true,
      imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop',
      isFreshPick: true,
    ),
    const ProductModel(
      id: 'prod_dairy_3',
      name: 'Premium Salted Butter',
      brand: 'DairyGold',
      categoryId: 'cat_dairy',
      rating: 4.8,
      reviewsCount: 280,
      price: 105.0,
      mrp: 120.0,
      discountText: '12% OFF',
      weightOptions: ['100g', '500g'],
      defaultWeight: '100g',
      description: 'Rich, creamy salted butter churned from pure pasture-raised cow milk. Perfect for spreading, baking, and cooking.',
      nutritionFacts: {'Calories': '717 kcal', 'Fat': '81g', 'Sodium': '643mg', 'Protein': '0.8g'},
      ingredients: ['Cream', 'Salt'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),

    // Bakery Products
    const ProductModel(
      id: 'prod_bak_1',
      name: 'Sourdough Country Loaf',
      brand: 'Bakehouse',
      categoryId: 'cat_bakery',
      rating: 4.9,
      reviewsCount: 150,
      price: 120.0,
      mrp: 140.0,
      discountText: '₹20 OFF',
      weightOptions: ['400g slice', 'Whole Loaf'],
      defaultWeight: '400g slice',
      description: 'Artisanal sourdough loaf baked daily. Golden, crispy crust with a soft, airy, and tangy interior. Leavened with wild natural yeast.',
      nutritionFacts: {'Calories': '220 kcal', 'Protein': '8g', 'Carbs': '45g', 'Fiber': '2g'},
      ingredients: ['Wheat Flour', 'Wild Yeast Starter', 'Water', 'Sea Salt'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=500&auto=format&fit=crop',
      isBestSeller: true,
    ),
    const ProductModel(
      id: 'prod_bak_2',
      name: 'Chocolate Chip Cookies',
      brand: 'Bakehouse',
      categoryId: 'cat_bakery',
      rating: 4.8,
      reviewsCount: 198,
      price: 150.0,
      mrp: 180.0,
      discountText: '16% OFF',
      weightOptions: ['6 pcs', '12 pcs'],
      defaultWeight: '6 pcs',
      description: 'Freshly baked soft-centered chocolate chip cookies loaded with rich Belgian dark chocolate chunks.',
      nutritionFacts: {'Calories': '480 kcal', 'Fat': '22g', 'Carbs': '65g', 'Protein': '5g'},
      ingredients: ['Wheat Flour', 'Belgian Chocolate Chips', 'Butter', 'Brown Sugar', 'Eggs'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
    const ProductModel(
      id: 'prod_bak_3',
      name: 'Whole Wheat Bread',
      brand: 'Bakehouse',
      categoryId: 'cat_bakery',
      rating: 4.6,
      reviewsCount: 230,
      price: 45.0,
      mrp: 55.0,
      discountText: '18% OFF',
      weightOptions: ['400g'],
      defaultWeight: '400g',
      description: 'Healthy and fiber-rich whole wheat sliced bread loaf, baked fresh daily with no added chemical preservatives.',
      nutritionFacts: {'Calories': '248 kcal', 'Protein': '12g', 'Carbs': '41g', 'Fiber': '7g'},
      ingredients: ['Whole Wheat Flour', 'Water', 'Yeast', 'Salt', 'Honey'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),

    // Snacks Products
    const ProductModel(
      id: 'prod_snack_1',
      name: 'Premium Roasted Cashews',
      brand: 'NutriBites',
      categoryId: 'cat_snacks',
      rating: 4.6,
      reviewsCount: 200,
      price: 349.0,
      mrp: 399.0,
      discountText: '12% OFF',
      weightOptions: ['200g', '500g'],
      defaultWeight: '200g',
      description: 'Perfectly dry-roasted whole cashews, lightly seasoned with sea salt. Sourced from the finest farms, high in healthy fats and proteins.',
      nutritionFacts: {'Calories': '553 kcal', 'Protein': '18g', 'Fat': '44g', 'Carbs': '30g'},
      ingredients: ['Cashews', 'Sea Salt'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
    const ProductModel(
      id: 'prod_snack_2',
      name: 'Classic Salted Potato Chips',
      brand: 'CrunchyCo',
      categoryId: 'cat_snacks',
      rating: 4.5,
      reviewsCount: 340,
      price: 30.0,
      mrp: 35.0,
      discountText: '14% OFF',
      weightOptions: ['80g', '150g'],
      defaultWeight: '80g',
      description: 'Thin, crispy gold-cut potato chips sprinkled with mineral sea salt. Made with high-quality potatoes.',
      nutritionFacts: {'Calories': '536 kcal', 'Protein': '7g', 'Fat': '35g', 'Carbs': '53g'},
      ingredients: ['Potatoes', 'Vegetable Oil', 'Sea Salt'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d20?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
    const ProductModel(
      id: 'prod_snack_3',
      name: 'Premium Mixed Nuts Pack',
      brand: 'NutriBites',
      categoryId: 'cat_snacks',
      rating: 4.8,
      reviewsCount: 215,
      price: 249.0,
      mrp: 299.0,
      discountText: '16% OFF',
      weightOptions: ['200g'],
      defaultWeight: '200g',
      description: 'A premium, healthy mixture of almonds, cashews, pistachios, and walnuts, lightly roasted to perfection.',
      nutritionFacts: {'Calories': '607 kcal', 'Protein': '20g', 'Fat': '54g', 'Carbs': '21g'},
      ingredients: ['Almonds', 'Cashews', 'Pistachios', 'Walnuts'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),

    // Meat & Seafood Products
    const ProductModel(
      id: 'prod_meat_1',
      name: 'Fresh Chicken Breast',
      brand: 'MeatMaster',
      categoryId: 'cat_meat',
      rating: 4.8,
      reviewsCount: 310,
      price: 299.0,
      mrp: 350.0,
      discountText: '15% OFF',
      weightOptions: ['500g', '1kg'],
      defaultWeight: '500g',
      description: 'Fresh, boneless, skinless lean chicken breast fillets. Rich in high-quality protein and perfect for baking, grilling, or stir-frying.',
      nutritionFacts: {'Calories': '165 kcal', 'Protein': '31g', 'Fat': '3.6g', 'Cholesterol': '85mg'},
      ingredients: ['Chicken Breast'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
    const ProductModel(
      id: 'prod_meat_2',
      name: 'Premium Salmon Fillet',
      brand: 'SeaFresh',
      categoryId: 'cat_meat',
      rating: 4.9,
      reviewsCount: 194,
      price: 899.0,
      mrp: 999.0,
      discountText: '₹100 OFF',
      weightOptions: ['250g', '500g'],
      defaultWeight: '250g',
      description: 'Premium fresh-water Atlantic salmon fillet. Rich in heart-healthy Omega-3 fatty acids, tender texture and rich flavor.',
      nutritionFacts: {'Calories': '208 kcal', 'Protein': '20g', 'Fat': '13g', 'Sodium': '59mg'},
      ingredients: ['Salmon Fillet'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500&auto=format&fit=crop',
      isBestSeller: true,
    ),
    const ProductModel(
      id: 'prod_meat_3',
      name: 'Tender Mutton Chops',
      brand: 'MeatMaster',
      categoryId: 'cat_meat',
      rating: 4.7,
      reviewsCount: 148,
      price: 699.0,
      mrp: 750.0,
      discountText: '₹51 OFF',
      weightOptions: ['500g'],
      defaultWeight: '500g',
      description: 'Juicy and tender premium mutton chops, cut from prime pasture-raised lamb. Sourced daily and hygienically packed.',
      nutritionFacts: {'Calories': '294 kcal', 'Protein': '25g', 'Fat': '21g', 'Iron': '15%'},
      ingredients: ['Mutton Chops'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),

    // Beverages Products
    const ProductModel(
      id: 'prod_drink_1',
      name: 'Sparkling Apple Juice',
      brand: 'FizzCider',
      categoryId: 'cat_drinks',
      rating: 4.7,
      reviewsCount: 192,
      price: 120.0,
      mrp: 150.0,
      discountText: '20% OFF',
      weightOptions: ['330ml', '750ml'],
      defaultWeight: '330ml',
      description: 'Refreshing sparkling juice made from 100% organic apples. Non-alcoholic, with no added sweeteners or colors.',
      nutritionFacts: {'Calories': '120 kcal', 'Carbs': '29g', 'Sugars': '28g', 'Vitamin C': '10%'},
      ingredients: ['Apple Juice', 'Carbonated Water'],
      isOrganic: true,
      imageUrl: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
    const ProductModel(
      id: 'prod_drink_2',
      name: 'Premium Cold Brew Coffee',
      brand: 'BrewLab',
      categoryId: 'cat_drinks',
      rating: 4.8,
      reviewsCount: 220,
      price: 160.0,
      mrp: 180.0,
      discountText: '11% OFF',
      weightOptions: ['250ml', '500ml'],
      defaultWeight: '250ml',
      description: 'Artisanal cold brew coffee steeped for 18 hours using single-origin Arabica beans. Bold, smooth flavor with low acidity.',
      nutritionFacts: {'Calories': '5 kcal', 'Carbs': '0g', 'Protein': '0g', 'Caffeine': '150mg'},
      ingredients: ['Cold Brew Coffee (Water, Arabica Coffee Beans)'],
      isOrganic: false,
      imageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
    const ProductModel(
      id: 'prod_drink_3',
      name: 'Organic Jasmine Green Tea',
      brand: 'EcoLeaf',
      categoryId: 'cat_drinks',
      rating: 4.9,
      reviewsCount: 135,
      price: 220.0,
      mrp: 250.0,
      discountText: '12% OFF',
      weightOptions: ['25 bags', '50 bags'],
      defaultWeight: '25 bags',
      description: 'Fragrant and soothing organic green tea leaves infused with natural jasmine flowers. High in natural antioxidants.',
      nutritionFacts: {'Calories': '0 kcal', 'Carbs': '0g', 'Protein': '0g', 'Antioxidants': 'High'},
      ingredients: ['Organic Green Tea', 'Organic Jasmine Flowers'],
      isOrganic: true,
      imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop',
      isFreshPick: false,
    ),
  ];

  static final List<Map<String, dynamic>> mockBanners = [
    {
      'title': 'Weekend Freshness',
      'subtitle': 'Up to 30% OFF on Organic Veggies',
      'tag': 'FLASH SALE',
      'gradient': [Color(0xFF4CAF50), Color(0xFF81C784)],
    },
    {
      'title': 'VIP Super Savings',
      'subtitle': 'Free Delivery on every single order',
      'tag': 'MEMBERSHIP',
      'gradient': [Color(0xFF1C1C1E), Color(0xFF3A3A3C)],
    },
    {
      'title': 'Farm to Kitchen',
      'subtitle': 'Harvested fresh at 4 AM every morning',
      'tag': 'OUR PROMISE',
      'gradient': [Color(0xFFFF9500), Color(0xFFFFB800)],
    },
  ];

  static final List<Map<String, dynamic>> mockCoupons = [
    {
      'code': 'FRESH50',
      'discount': '₹50 OFF',
      'description': 'Applicable on orders above ₹499',
      'minOrder': 499.0,
      'value': 50.0,
    },
    {
      'code': 'SUPERVIP',
      'discount': '10% OFF',
      'description': 'Maximum discount of ₹100',
      'minOrder': 299.0,
      'value': 0.1, // percentage indicator
    },
    {
      'code': 'FREEFORTY',
      'discount': '₹40 OFF',
      'description': 'On organic dairy items',
      'minOrder': 199.0,
      'value': 40.0,
    }
  ];

  static final List<Map<String, dynamic>> mockAddresses = [
    {
      'id': 'addr_1',
      'tag': 'Home',
      'receiverName': 'John Doe',
      'addressLine': 'Flat 402, Apple Heights, Sector 12',
      'city': 'Bengaluru',
      'pincode': '560103',
      'phone': '+91 9876543210',
      'isDefault': true,
    },
    {
      'id': 'addr_2',
      'tag': 'Office',
      'receiverName': 'John Doe',
      'addressLine': 'Building 3A, Tech Park East, Bellandur',
      'city': 'Bengaluru',
      'pincode': '560103',
      'phone': '+91 9876543210',
      'isDefault': false,
    }
  ];

  static Future<void> syncWithServer(String apiBaseUrl) async {
    try {
      final dio = Dio();
      final pRes = await dio.get('$apiBaseUrl/products');
      if (pRes.data != null && pRes.data['success'] == true) {
        final List<dynamic> pList = pRes.data['products'];
        products.clear();
        for (var p in pList) {
          products.add(ProductModel.fromJson(Map<String, dynamic>.from(p)));
        }
        debugPrint('✅ Flutter Products synced with MERN Backend: ${products.length} items');
      }

      final cRes = await dio.get('$apiBaseUrl/categories');
      if (cRes.data != null && cRes.data['success'] == true) {
        final List<dynamic> cList = cRes.data['categories'];
        categories.clear();
        for (var c in cList) {
          categories.add(CategoryModel.fromJson(Map<String, dynamic>.from(c)));
        }
        debugPrint('✅ Flutter Categories synced with MERN Backend: ${categories.length} items');
      }
      
      final cpRes = await dio.get('$apiBaseUrl/coupons');
      if (cpRes.data != null && cpRes.data['success'] == true) {
        final List<dynamic> cpList = cpRes.data['coupons'];
        mockCoupons.clear();
        for (var cp in cpList) {
          mockCoupons.add({
            'code': cp['code'],
            'discount': cp['discount'],
            'description': cp['description'],
            'minOrder': (cp['minOrder'] as num).toDouble(),
            'value': (cp['value'] as num).toDouble(),
          });
        }
        debugPrint('✅ Flutter Coupons synced with MERN Backend');
      }
    } catch (e) {
      debugPrint('⚠️ Failed to sync with MERN Server: $e. Operating in offline mock data mode.');
    }
  }
}

